language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libimage-exiftool-perl imagemagick
  - exiftool -ver

install:
  - bundle install --path vendor/bundle

before_script:
  - mysql -e 'create database AssetHost_test'

script: 
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

services:
  - mysql

cache: bundler

rvm:
  - 2.3

env:
  - ASSETHOST_HOST_PROTOCOL=http
  - SH=bash
  - PACKAGE_VERSION="1.0.*"