## Don't worry, there's nothing actually secret in this file.  It's definitely supposed to be here.

vars: &default
  secret_key_base:    <%= ENV["ASSETHOST_SECRET_KEY_BASE"] %>
  flickr_api_key:     <%= ENV["ASSETHOST_FLICKR_API_KEY"] %>
  brightcove_api_key: <%= ENV["ASSETHOST_BRIGHTCOVE_API_KEY"] %>
  google_api_key:     <%= ENV["ASSETHOST_GOOGLE_API_KEY"] %>
  resque:
    host: <%= ENV["ASSETHOST_RESQUE_HOST"] %>
    port: <%= ENV["ASSETHOST_RESQUE_PORT"] || 6379  %>
  elasticsearch: 
    host: <%= ENV["ASSETHOST_ELASTICSEARCH_HOST"] %>
  s3:
    bucket: <%= ENV["ASSETHOST_S3_BUCKET"] %>
    region: <%= ENV["ASSETHOST_S3_REGION"] %>
    endpoint: <%= ENV["ASSETHOST_S3_ENDPOINT"] %>
    signature_version: <%= ENV["ASSETHOST_S3_SIGNATURE_VERSION"] %>
    access_key_id:     <%= ENV["ASSETHOST_S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["ASSETHOST_S3_SECRET_ACCESS_KEY"] %>
  rekognition:
    region: <%= ENV["ASSETHOST_REKOGNITION_REGION"] %>
    access_key_id:     <%= ENV["ASSETHOST_REKOGNITION_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["ASSETHOST_REKOGNITION_SECRET_ACCESS_KEY"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

